### PR TITLE
Updated README for Paypal SDK 1.3.0 for Laravel 4

### PR DESCRIPTION
**Pull request by webwizo**

### CODE REVIEW

**Comment by webwizo** [comment]
Yes, I know about it. A big change is Address Class, Paypal allows only Phone Number properties in Address Class, all customer contact related fields are removed. Please check it out.

**Comment by xroot** [comment]
yes you're right I just noticed that here https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Address.php

**Comment by webwizo** [comment]
You're right, I didn't see this carefully. Sorry, my mistake :)

**Comment by xroot** [comment]
ok no worries I have fixed the doc

**Comment by webwizo** [comment]
Thank you! =)

**Pull request closed without merging**
